version: '3.9'

services:
  beer-club-colombia-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: beer-club-colombia-api
    restart: always
    ports:
      - "8000:8000"

    networks:
      - beer-club-colombia-network

networks:
  beer-club-colombia-network:
    driver: bridge